spring.application.name: grpc-server
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
      - monitoring.yml
  main.web-application-type: none
  sleuth:
    grpc:
      enabled: true

grpc:
  port: 8081
  in-process-server-name: grpc-server
  shutdown-grace: 30 # seconds

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: production
