spring.application.name: grpc-client
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

grpc.server:
  address: localhost
  port: 8081

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: production
